### ISSUE TITLE
Crashes at initialisation on JDK 17

### ISSUE THREAD

**Issue by tOverney** [squeryl/squeryl#340]
Version of Squeryl tried: 0.9.14 and 0.9.16
When starting my program using JDK11 everything "just works"
But when I switch to JDK17 Some reflective call in Squeryl just blows up (seems some internal jdk method changed accessibility):

```
java.lang.ExceptionInInitializerError:
at org.squeryl.internals.PosoMetaData.<init>(PosoMetaData.scala:212)
at org.squeryl.View.<init>(View.scala:65)
at org.squeryl.Table.<init>(Table.scala:27)
at org.squeryl.Schema.table(Schema.scala:346)
...
Cause: net.sf.cglib.core.CodeGenerationException: java.lang.reflect.InaccessibleObjectException-->Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @11011324
at net.sf.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:464)
at net.sf.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:339)
at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:96)
at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:94)
at net.sf.cglib.core.internal.LoadingCache$2.call(LoadingCache.java:54)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at net.sf.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:61)
at net.sf.cglib.core.internal.LoadingCache.get(LoadingCache.java:34)
at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:119)
at net.sf.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:294)
...
Cause: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @11011324
at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
at net.sf.cglib.core.ReflectUtils$1.run(ReflectUtils.java:61)
at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
at net.sf.cglib.core.ReflectUtils.<clinit>(ReflectUtils.java:52)
at net.sf.cglib.core.KeyFactory$Generator.generateClass(KeyFactory.java:243)
at net.sf.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
at net.sf.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:332)
```

**Comment by bchazalet** [comment]
squeryl has a dependency on cglib, for which compatibility for JDK 16 and 17 is known to be problematic. See for example: https://github.com/cglib/cglib/issues/191

**Comment by papirosko** [comment]
any idea on how to fix this? following the url they advice to use ByteBuddy

**Comment by gabrieljones** [comment]
These VM options got it working:
> ```--add-exports=java.naming/com.sun.jndi.ldap=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.security=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.management/javax.management=ALL-UNNAMED --add-opens=java.naming/javax.naming=ALL-UNNAMED```
> https://github.com/cglib/cglib/issues/191#issuecomment-1181253120

But I don't feel comfortable running those in production.

**Comment by bchazalet** [comment]
in the test, squeryl uses `--add-opens=java.base/java.lang=ALL-UNNAMED` only, and this seems to cover it.

**Comment by pbrant** [comment]
I moved a fork of ours to ByteBuddy with comparatively little effort. We're
using it with JDK 21 with no special configuration.

I just tried cherry picking it to master and there were a number of
conflicts. I don't think the fundamental approach in this area of the code
has changed significantly here though. It shouldn't be too bad to adapt to
current master.

Link here
https://github.com/ccap/Squeryl/commit/c7114ab1de810ba61409afe2108baacb4d79a144
